### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by mjuric** [scimma/client_library#32]
We should add a `requirements.txt` file with all the dependencies necessary to develop the package, so a dev can do:
```
pip install -r requirements.txt
```
to get themselves started. This will largely be a union of packages mentioned in `install_requires` and `extras_require` variables in `setup.py`.

P.S.: We may need to add a separate `conda-requirements.txt`, in case there are any packages where the PyPI name is different from the `conda` package name.

**Comment by adambrazier** [comment]
Also it's best to specify specific known-good version numbers, rather than >=, as in a few years ago those can bite us...On Feb 11, 2020 8:24 PM, Mario Juric <notifications@github.com> wrote:We should add a requirements.txt file with all the dependencies necessary to develop the package, so a dev can do:
pip install -r requirements.txt

to get themselves started. This will largely be a union of packages mentioned in install_requires and extras_require variables in setup.py.
P.S.: We may need to add a separate conda-requirements.txt, in case there are any packages where the PyPI name is different from the conda package name.
