### ISSUE TITLE
Publish documentation to RTD

### ISSUE THREAD

**Issue by mjuric** [scimma/client_library#7]
As a user, I want to be able to browse the documentation published as HTML on [RTD](https://readthedocs.org/).

Definition of done:
 - I must be able to go to (say) https://readthedocs.org/projects/scimma to see the documentation for the latest published (i.e., tagged with a version) scimma client
 - I must be able to select and view the documentation for any older version.

Tasks
- [x] Learn how RTD works, create account, etc.
- [x] Make sure at least @adambrazier @mjuric have access to our RTD
- [ ] Implement and document in the README.md the documentation creation and upload process
- [x] Publish at least two versions of the documentation (so all functionality can be tested).

**Comment by myNameIsPatrick** [comment]
@mjuric, @adambrazier, in order to accomplish 2, you'll need to sign up for an RTD account to have access to the project dashboard: https://readthedocs.org/dashboard/. It also seems like we'll need to set up a webhook for RTD to trigger on tags/commits to build docs. The guide to set up the RTD webhook in the project settings is here, which requires admin access to set up: https://docs.readthedocs.io/en/stable/webhooks.html#github.

**Comment by mjuric** [comment]
@bfc5288 -- can you see if you can do whatever is needed (@adambrazier, I gave Bryce temporary admin rights to the scimma GitHub org to remove the two of us as potential blockers while a lot of infrastructure work is going on).

**Comment by bfc5288** [comment]
@myNameIsPatrick The RTD webhook has been added.

**Comment by mjuric** [comment]
@myNameIsPatrick Opened an account; my RTD username is 'mjuric'

**Comment by myNameIsPatrick** [comment]
@mjuric, I added you as a maintainer for the scimma-client project.

**Comment by myNameIsPatrick** [comment]
Waiting for #5 so that we can release a new proper version with the necessary RTD config so we can test out the release part of the RTD docs.

**Comment by adambrazier** [comment]
@bfc5288 I'm adambrazier on RTD

**Comment by myNameIsPatrick** [comment]
@adambrazier, you've been added now.
